# Generated by Django 4.2.2 on 2023-07-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название вложения",
                        max_length=255,
                        verbose_name="Название вложения",
                    ),
                ),
                (
                    "content",
                    models.BinaryField(
                        help_text="Содержимое вложения",
                        verbose_name="Содержимое вложения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение",
                "verbose_name_plural": "Вложения",
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Дата создания",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "date_edited",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата изменения",
                        null=True,
                        verbose_name="Дата редактирования",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Собеседник ответил пользователю",
                        verbose_name="Активен ли чат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чат",
                "verbose_name_plural": "Чаты",
                "ordering": ["-date_created"],
                "get_latest_by": "date_created",
            },
        ),
        migrations.CreateModel(
            name="ChatMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Дата создания",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "chat_is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Пользователь закрепил этот чат для себя",
                        verbose_name="Закреплён ли чат",
                    ),
                ),
                (
                    "chat_is_cleared",
                    models.BooleanField(
                        default=False,
                        help_text="Удалены все сообщения в чате пользователем",
                        verbose_name="Очищен ли чат",
                    ),
                ),
                (
                    "is_creator",
                    models.BooleanField(
                        default=False,
                        help_text="Этот пользователь начал переписку в чате",
                        verbose_name="Является ли создателем чата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник",
                "verbose_name_plural": "Участники",
                "ordering": ["-date_created"],
                "get_latest_by": "date_created",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Дата создания",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "date_edited",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата изменения",
                        null=True,
                        verbose_name="Дата редактирования",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Текст сообщения",
                        max_length=5000,
                        verbose_name="Текст сообщения",
                    ),
                ),
                (
                    "file_to_send",
                    models.FileField(
                        blank=True,
                        help_text="Файл для отправки",
                        null=True,
                        upload_to="files_to_send/",
                        verbose_name="Файл для отправки",
                    ),
                ),
                (
                    "sender_keep",
                    models.BooleanField(
                        default=False,
                        help_text="Сообщение отправлено",
                        verbose_name="Сообщение отправлено",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Сообщение прочитано",
                        verbose_name="Сообщение прочитано",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Сообщение закреплено",
                        verbose_name="Сообщение закреплено",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="MessageReaders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="Сообщение, которое было прочитано",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chats.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Читатель сообщения",
                "verbose_name_plural": "Читатели сообщений",
            },
        ),
    ]
